version: "3"
services:
    nginx:
        image: gihyodocker/nginx-proxy
        deploy:
            replicas: 2 
            placement: 
                constraints: [node.role != manager]
        environment: 
            BACKEND_HOST: simple-web_api:8000
        depends_on:
            - api
        networks:
            - ch03
        ports:
            - 80:80
    api:
        image: jenkins-server:5000/example/simple-web:latest            
        deploy:
            replicas: 3
            placement:
                constraints: [node.role != manager]
        networks:
            - ch03
networks:
    ch03:
        external: true